//---------------------------------- 常规设定 ----------------------------------
{$DEFINE Debug}
//调试模式

//----------------------------------- 管理器 -----------------------------------
{.$DEFINE RemObjects}
//启用通道管理器

{.$DEFINE TaskMonitor}
//启用任务管理器

{.$DEFINE PlugManager}
//启用插件管理器

{$DEFINE LogManager}
//启用日志管理器

{$DEFINE DBManager}
//启用数据库管理器

{.$DEFINE MenuManager}
//启用数据库管理器

{.$DEFINE MQTTMessager}
//启用MQTT消息中心
